name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - dev
      - feature/**
      - feat/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Bandit Test
        uses: mdegis/bandit-action@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: high
          confidence: high
          exit_zero: true