name: Consumer CI

on:
    push:
        branches: [main, dev, feature/consumer]
    pull_request:
        branches: [main, dev]

env:
  IMAGE_NAME: tsmc-hackathon-2024-consumer 
  DOCKER_FILE_PATH: ./consumer # '.' for root directory
  WHEEL_CI_SERVICE_NAME: consumer
  WHEEL_CI_SERVICE_HOST: https://quickly-renewing-lobster.ngrok-free.app 

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Set up containerd
              uses: crazy-max/ghaction-setup-containerd@v3
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              uses: docker/build-push-action@v4
              with:
                context: ${{ env.DOCKER_FILE_PATH }}
                platforms: linux/amd64,linux/arm64
                tags: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
                outputs: type=oci,dest=/tmp/image.tar
            - name: Import image in containerd
              run: |
                sudo ctr i import --base-name docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest --digests --all-platforms /tmp/image.tar
            - name: Push image to containerd
              run: |
                sudo ctr i push --user "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            - name: Trigger webhook using curl
              run: |
                curl -X POST -H "Content-Type: application/json" -d '{"token": "${{ secrets.WHEEL_CI_TOKEN }}"}' ${{ env.WHEEL_CI_SERVICE_HOST }}/api/v1/webhooks/github/service${{ env.WHEEL_CI_SERVICE_NAME }}

